# Generated by Django 5.1 on 2024-09-12 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(choices=[('tokopedia', 'Tokopedia'), ('shopee', 'Shopee')], max_length=255)),
                ('sku', models.CharField(help_text='sku of product', max_length=255)),
                ('name', models.CharField(help_text='name of product', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, help_text='price of product', max_digits=5)),
                ('stock', models.PositiveIntegerField(default=0, help_text='stock of product')),
            ],
            options={
                'verbose_name': 'Marketplace Product',
                'ordering': ('identifier',),
                'unique_together': {('identifier', 'sku')},
            },
        ),
    ]
