# Generated by Django 5.1 on 2024-09-12 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BulkProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='main/products')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done')], default='pending', max_length=100)),
                ('progress', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Channels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Channel',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(help_text='aka Invoice Number', max_length=100)),
                ('order_id', models.CharField(blank=True, help_text='Order ID on Marketplace', max_length=100, null=True)),
                ('marketplace', models.CharField(blank=True, help_text='Marketplace Name eg: Tokopedia, Shopee etc', max_length=100, null=True)),
                ('order_date', models.DateTimeField(auto_now=True)),
                ('total_price', models.FloatField()),
            ],
            options={
                'verbose_name': 'Orders',
                'ordering': ('order_number',),
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('stock', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Product',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('total_price', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.orders')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.products')),
            ],
            options={
                'verbose_name': 'Order Details',
                'ordering': ('order',),
            },
        ),
    ]
