# Generated by Django 5.1 on 2024-09-11 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_bulkproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkproducts',
            name='file',
            field=models.FileField(upload_to='main/products'),
        ),
    ]
