# Generated by Django 5.1 on 2024-09-11 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_bulkproducts_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkproducts',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
