# Generated by Django 5.1 on 2024-09-12 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_bulkproducts_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='marketplace',
            field=models.CharField(blank=True, help_text='Marketplace Name eg: Tokopedia, Shopee etc', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_id',
            field=models.CharField(blank=True, help_text='Order ID on Marketplace', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bulkproducts',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done')], default='pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_number',
            field=models.CharField(help_text='aka Invoice Number', max_length=100),
        ),
    ]
